## 로그관련 설정
# 로그 색상
spring.output.ansi.enabled=always
# 로그레벨 설정
logging.level.root=info
# Logging (SQL 파라미터까지 보이게)
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Server
server.port=8080

# DataSource (Oracle XE - Docker)
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE
spring.datasource.username=roomy
spring.datasource.password=java12345
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Session
server.servlet.session.timeout=30m
